name: CI Tests

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: cd client && npm install --production=false

      - name: Lint client
        run: cd client && npm run lint

      - name: Test client
        run: cd client && npm test
