name: Lint

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./client
      - name: Install Packages
        run: npm install --production=false
        
      - name: Lint
        run: npm run lint
