name: Lint

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./client
      - name: Install Packages
        run: cd ./client npm install --production=false
        
      - name: Lint
        run: cd ./client && npm run lint
