name: Lint

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Packages
        working-directory: ./client
        run: npm install --production=false
        
      - name: Lint
        working-directory: ./client
        run: npm run lint
